### ISSUE TITLE
error when trying renew password

### ISSUE THREAD

**Issue by rodinux** [YunoHost-Apps/galette_ynh#15]
### Describe the bug

*I can't renew the password if the members, There is twoo option, a link "New password" on the profil members or when disconnected the link "Password Forgotten", the two make an error

### Context

Once installed Galette and import with success members, I have configured the mail with the smtp of the yunohost server and I can test it, it works. 
The only thing wrong is if I want to use the 'New Password" which is used to sent a link at the member's mail to renew his password or the option in the "Forgot my password" before be connected, which may do the same operation.

- Hardware: *Public Cloud bought online
- YunoHost version: 4.2.8.3
- I have access to my server: *Through SSH | through the webadmin *
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no 
- Using, or trying to install package version/branch: master

### Expected behavior

I have import a lot of members and now I need to sent them the information with a link to renew their password. 

### Logs

I can see this error in `/var/log/nginx/ecranvillage.ovh-error.log`

```
2021/10/12 00:02:18 [error] 15866#15866: *144649 FastCGI sent in stderr: "PHP message: Galette error:
Type: RuntimeException
Message: Patterns and replacements does not match!
File: /var/www/galette/galette/lib/Galette/Features/Replacements.php
Line: 878
Trace: #0 /var/www/galette/galette/lib/Galette/Entity/Texts.php(529): Galette\Entity\Texts->proceedReplacements('[{ASSO_NAME}] V...')
#1 /var/www/galette/galette/lib/Galette/Controllers/AuthController.php(337): Galette\Entity\Texts->getSubject()
#2 [internal function]: Galette\Controllers\AuthController->retrievePassword(Object(Slim\Http\Request), Object(Slim\Http\Response), 1)
#3 /var/www/galette/galette/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array(Array, Array)
#4 /var/www/galette/galette/vendor/php-di/slim-bridge/src/ControllerInvoker.php(50): Invoker\Invoker->call(Array, Array)
#5 /var/www/galette/galette/vendor/slim/slim/Slim/Route.php(281): DI\Bridge\Slim\ControllerInvoker->__invoke(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#6 /var/www/galette/galette/vendor/slim/slim/" while reading response header from upstream, client: 2a01:e0a:94:50:c9d0:b2d2:7439:767d, server: ecranvillage.ovh, request: "GET /galette/retrieve-pass/1 HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm-galette.sock:", host: "ecranvillage.ovh", referrer: "https://ecranvillage.ovh/galette/member/1"
```

Is it an error with php ? or nginx ?

here the log in the file `/var/www/galette/galette/data/logs/galette.log`

```
2001:xxxx:xxx:xxxx::xxx - 2021-10-11 23:07:01 - DEBUG - New passwords temporary set for `1`.
2001:xxxx:xxx:xxxx::xxx - 2021-10-11 23:07:01 - ERROR - Galette error:
Type: RuntimeException
Message: Patterns and replacements does not match!
File: /var/www/galette/galette/lib/Galette/Features/Replacements.php
Line: 878
Trace: #0 /var/www/galette/galette/lib/Galette/Entity/Texts.php(529): Galette\Entity\Texts->proceedReplacements('[{ASSO_NAME}] V...')
#1 /var/www/galette/galette/lib/Galette/Controllers/AuthController.php(337): Galette\Entity\Texts->getSubject()
#2 [internal function]: Galette\Controllers\AuthController->retrievePassword(Object(Slim\Http\Request), Object(Slim\Http\Response), 1)
#3 /var/www/galette/galette/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array(Array, Array)
#4 /var/www/galette/galette/vendor/php-di/slim-bridge/src/ControllerInvoker.php(50): Invoker\Invoker->call(Array, Array)
#5 /var/www/galette/galette/vendor/slim/slim/Slim/Route.php(281): DI\Bridge\Slim\ControllerInvoker->__invoke(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#6 /var/www/galette/galette/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#7 /var/www/galette/galette/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#8 /var/www/galette/galette/vendor/slim/slim/Slim/App.php(503): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#9 /var/www/galette/galette/vendor/akrabat/rka-slim-session-middleware/RKA/SessionMiddleware.php(47): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#10 [internal function]: RKA\SessionMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Galette\Core\SlimApp))
#11 /var/www/galette/galette/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(RKA\SessionMiddleware), Array)
#12 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Galette\Core\SlimApp))
#13 /var/www/galette/galette/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Galette\Core\SlimApp))
#14 /var/www/galette/galette/lib/Galette/Middleware/TrailingSlash.php(81): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#15 [internal function]: Galette\Middleware\TrailingSlash->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#16 /var/www/galette/galette/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Galette\Middleware\TrailingSlash), Array)
#17 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#18 /var/www/galette/galette/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#19 /var/www/galette/galette/lib/Galette/Middleware/Language.php(104): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#20 [internal function]: Galette\Middleware\Language->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#21 /var/www/galette/galette/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Galette\Middleware\Language), Array)
#22 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#23 /var/www/galette/galette/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#24 /var/www/galette/galette/lib/Galette/Middleware/Telemetry.php(146): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#25 [internal function]: Galette\Middleware\Telemetry->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#26 /var/www/galette/galette/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Galette\Middleware\Telemetry), Array)
#27 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#28 /var/www/galette/galette/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#29 /var/www/galette/galette/lib/Galette/Middleware/CheckAcls.php(144): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#30 [internal function]: Galette\Middleware\CheckAcls->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#31 /var/www/galette/galette/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Galette\Middleware\CheckAcls), Array)
#32 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#33 /var/www/galette/galette/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure))
#34 /var/www/galette/galette/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#35 /var/www/galette/galette/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#36 /var/www/galette/galette/vendor/slim/slim/Slim/App.php(297): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#37 /var/www/galette/galette/includes/main.inc.php(155): Slim\App->run()
#38 /var/www/galette/galette/webroot/index.php(57): require_once('/var/www/galett...')
#39 {main}
```

**Comment by rodinux** [comment]
The PR #17 has fixed this issue.

**Comment by rodinux** [comment]
the merge from testing close this issue, Thanks !
